## Module 2 Class activities
This notebook is a starting point for the exercises and activities that we'll do in class.

Before you attempt any of these activities, make sure to watch the video lectures for this module.

### Scraping permit data
Here's the code that we saw in the video lecture that queries the City of Seattle permit website, gets a dataframe of permits (including the URL), and then digs down further into that permit-specific URL.

In [2]:
# get the permit data from the API
import json
import requests
import pandas as pd
from bs4 import BeautifulSoup

url = 'https://data.seattle.gov/resource/ht3q-kdvx.json' # copied and pasted from the webpage
r = requests.get(url)
df = pd.DataFrame(json.loads(r.text))

df = df.head(8) # get the first 5 rows, so we don't overload the city's website.

# get an example link
permiturl = df.loc[7,'link']['url']
print(permiturl)

# request that page and get the soup object
r = requests.get(permiturl)
soup = BeautifulSoup(r.text)
print(soup.prettify())

https://services.seattle.gov/portal/customize/LinkToRecord.aspx?altId=3001610-LU
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US" ng-app="appAca" xml:lang="en-US" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
 <head id="ctl00_Head1">
  <link href="../App_Themes/Default/form.css" rel="stylesheet" type="text/css"/>
  <link href="../App_Themes/Default/style.css" rel="stylesheet" type="text/css"/>
  <title>
   Accela Citizen Access
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <style type="text/css">
   body, html {
        overflow-y: visible!important;
        }
        .page-overlay-blocker {
          position: fixed;
          z-index: 999;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          width: 100%;
          height: 100%;
          background-color: #ffffff;
          opacity: 0.1;
          display:none;
        }
  </style>
  <link href="../css/main.css" rel="stylesheet" type="text/css"/>
  <link href="../css/acaresponsive.min.css" rel="stylesheet" type="text/css"/>
  <script src="/Portal/bundles/aca-gis?v=qZBQzLf2g-HLVKRpUwySmf0HSY9NU1VUc_xUbESbAAs1">
  </script>
  <link href="../App_Themes/en-US/style.css" rel="stylesheet" type="text/css"/>
  <link href="/Portal/Handlers/CustomizedCssStyle.ashx?agencyCode=SEATTLE" id="ctl00_CustomerCssStyle" rel="stylesheet" style="text/css"/>
  <link href="/Portal/Customization/SEATTLE/globalcustomscriptbefore.css" id="ctl00_PageCustomizeCssStyle_GlobalCustomScriptBefore" rel="stylesheet" style="text/css"/>
  <link href="/Portal/Customization/SEATTLE/cap/capdetail.css" id="ctl00_PageCustomizeCssStyle_/cap/CapDetail" rel="stylesheet" style="text/css"/>
  <link href="/Portal/Customization/SEATTLE/globalcustomscriptafter.css" id="ctl00_PageCustomizeCssStyle_GlobalCustomScriptAfter" rel="stylesheet" style="text/css"/>
 </head>
 <script type="text/javascript">
  var firstErrorMsgId;

    function isSafari(){
        var ua = window.navigator.userAgent;
        return ua.indexOf("Safari")>-1;
    }

    var original=0;
    function iframeAutoFit()
    {
        try
        {
            if(window!=parent)
            {
                var ifrm = getParentDocument().getElementById("ACAFrame");
                if(ifrm != null && ifrm.contentWindow==window)
                {
                    var h1 = 0, h2 = 0;

                    if(document.documentElement&&document.documentElement.scrollHeight)
                    {
                        h1=ifrm.contentWindow.document.documentElement.scrollHeight;
                    }
                    if (isSafari()) {
                        h1=ifrm.contentWindow.document.body.scrollHeight;
                    }

                    var h=$(ifrm.contentWindow.document.body).innerHeight();

                    var temp = h1-60 - h;
                    var chk = true;
                    if (temp> 0 && temp<200) {
                        chk = false;
                    }

                    var popupHeight = 0;
                    var popupDialog = $("#dvACADialogLayer");
                    if ($.exists(popupDialog)) {
                        popupHeight = popupDialog[0].clientHeight;
                        if (h < popupHeight) {
                            h = popupHeight;
                        }
                    }

                    if(original != h || !chk){
                        if(isFireFox() == false)
                        {
                            if (chk) {
                                h1 = parseInt(h)+60;
                            }

                            ifrm.style.height = ifrm.parentNode.style.height = h1 +"px";
                        }
                        else
                        {
                            if (chk) {
                                if ($.exists(popupDialog)) {
                                    h1 = parseInt(h) + 60;
                                } else {
                                    h1 = ifrm.contentDocument.body.scrollHeight;
                                    h1 = parseInt(h1) + 60;
                                }
                            }

                            ifrm.height = h1;
                        }

                        original = h;
                    }
                }
            }
        }
        catch (ex){}
    }
 </script>
 <body>
  <div class="page-overlay-blocker" id="iframeBlocker">
  </div>
  <script src="/Portal/Scripts/GlobalConst.aspx" type="text/javascript">
  </script>
  <script src="/Portal/bundles/common?v=3frcyczFCCAemuR09W71PpqoQkdwvQy6MShBSNrJdrc1">
  </script>
  <script src="/Portal/bundles/accela-common?v=kGpULZyk87MIozcGFavDaYJA7XTn5nETLZ6ByrnGnac1">
  </script>
  <script src="/Portal/Scripts/SessionTimeout.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   $.global.isRTL = IsTrue('False');

        //fix the issue that the confirm/alert box should also follows the current culture.
        if ($.global.isRTL) {
            document.dir = "rtl";
        } else {
            document.dir = "";
        }

        $.global.isAdmin = IsTrue('False');
        var isClassTemplate = IsTrue('True');
        var isWelcomePage = IsTrue('False');
        var isLoginPage = IsTrue('False');
        var isAnonymous = IsTrue('True');
        var isCapApplyDisclaimerPage = IsTrue('False');
        var isCapEditPage = IsTrue('False');

        if (!isAnonymous && !$.global.isAdmin) {
            var opts = {
                Culture: 'en-US',
                TimeoutTime: 30,
                WarningTime: 5,
                WarnTitle: 'Warning',
                ExpiredTitle: 'Session Expired',
                MsgWarn: 'Your session will time out in {0} minute(s). Would you like to continue?',
                MsgExpired: 'Your session has been timed out due to inactivity. Please click on Login to access your account.',
                MsgHelp: 'Please press the Tab key to move the focus to the OK or Cancel button.',
                BtnOK: 'OK',
                BtnCancel: 'Cancel',
                BtnLogin: 'Login',
                UrlWelcome: '/Portal/Welcome.aspx',
                UrlLogin: '/Portal/Login.aspx',
                UrlLogic: '/Portal/Handlers/SessionTimeOutHandler.ashx',
                UrlCloseImg: '/Portal/app_themes/Default/assets/closepopup.png',
                UrlUserStatus: '/Portal/api/PublicUser/AccountStatus',
                ApplicationRoot: '/Portal/'
            };

            if (isClassTemplate) {
                $("body").SessionTimeoutTimer(opts);
            }
        }
  </script>
  <script type="text/javascript">
   var walkMeOptions = '{"userID":"31BCA02094EB78126A517B206A88C73CFA9EC6F704C7030D18212CACE820F025F00BF0EA68DBF3F3A5436CA63B53BF7BF80AD8D5DE7D8359D0B7FED9DBC3AB99","module":"DPDPermits","userGroup":"Anonymous","walkMeJsUrl":"https://cdn.walkme.com/users/01c65c34a5d141bbac172b11d8b9fcbf/walkme_01c65c34a5d141bbac172b11d8b9fcbf_https.js"}';

    if (walkMeOptions != undefined && walkMeOptions != null && walkMeOptions.length != 0) {
        var walkMeData = JSON.parse(walkMeOptions);
        if (walkMeData.walkMeJsUrl != undefined && walkMeData.walkMeJsUrl != null && walkMeData.walkMeJsUrl.length != 0) {
            var accelaVariables = new Object()
            accelaVariables.userId = walkMeData.userID;
            accelaVariables.userGroup = walkMeData.userGroup;
            accelaVariables.product = walkMeData.product;
            accelaVariables.version = walkMeData.version;
            accelaVariables.environment = walkMeData.environment;
            accelaVariables.module = walkMeData.module;
            accelaVariables.agency = walkMeData.agency;
            window.accelaVariables = accelaVariables;

            //How to Pass Agency Name?
            (function () {
                var walkme = document.createElement('script');
                walkme.type = 'text/javascript';
                walkme.async = true;
                walkme.src = walkMeData.walkMeJsUrl;
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(walkme, s);
                window._walkmeConfig = { smartLoad: true };
            })();
        }
    }
  </script>
  <script>
   (function(h,o,u,n,d) {
     h=h[d]=h[d]||{q:[],onReady:function(c){h.q.push(c)}}
     d=o.createElement(u);d.async=1;d.src=n
     n=o.getElementsByTagName(u)[0];n.parentNode.insertBefore(d,n)
  })(window,document,'script','https://www.datadoghq-browser-agent.com/datadog-rum-v4.js','DD_RUM')
  DD_RUM.onReady(function() {
    DD_RUM.init({
      clientToken: 'pub4c296e8a953a31a53abb3617c2f840e4',
      applicationId: 'e34bafed-755d-4362-89e6-2ea4af60cd0f',
      site: 'datadoghq.com',
      env: 'civp_prod_azure',
      service: 'aca',
      version: '25.2.1.250404',
      sampleRate: 10,
      sessionReplaySampleRate: 5,
      premiumSampleRate: 5,
      trackInteractions: true
    })
  })
  </script>
  <div class="" id="divctl00_hlSkipToolBar" style="WIDTH: 0px; HEIGHT: 0px;">
   <a accesskey="1" class="NotShowLoading" href="#FirstAnchorInACAMainContent" id="ctl00_hlSkipToolBar" onclick="skipToMainContent();" tabindex="-1" title="Skip Module Navigation">
    <img alt="Skip Module Navigation" height="0px" src="/Portal/WebResource.axd?d=_srwWNS1MSJOYH4C35b1oFn7VEYtvNa8YGGRg1sqtrF_faY_-fd0egWACbQyGWVnyPpONGyWOQylydrXXpHjvXdl4T0G4TrJ5TZlCzCCz424pMVoF3uq-ZWyjKkSQo7UFVPfshRXWd-tDgOs0est9E0Mlus1&amp;t=638778359120000000" style="border-width:0px;" width="0px"/>
   </a>
  </div>
  <form action="./CapDetail.aspx?type=1000&amp;fromACA=Y&amp;agencyCode=SEATTLE&amp;Module=DPDPermits&amp;capID1=05HST&amp;capID2=00000&amp;capID3=19813" id="aspnetForm" method="post" name="aspnetForm">
   <input id="ACA_CS_FIELD" name="ACA_CS_FIELD" type="hidden" value="670d5fafd619492ea3db41bcd4d8278d"/>

In [81]:
# then we wrote this code to extract the project description 
links = soup.find_all('td')
for link in links:
    if 'Project Description' in link.text: 
        sublinks = link.find_all('td')
        description = sublinks[1].text
        # once we find a description, we exit
        break
    
print(description)

Land Use Application to subdivide one development site into six unit lots. The construction of residential units has been approved under Project #2503285/6100827. This subdivision of property is only for the purpose of allowing sale or lease of the unit lots.  Development standards will be applied to the original parcel and not to each of the new unit lots.

<div class="alert alert-block alert-info">
<strong>Exercise:</strong> If you look at the example, there may be a section giving information on the number of curb cuts. Extract that to a variable and print it.
</div>

In [9]:
# Hints
# Not all of the records have the curb cut field. You can see an example here:
# https://services.seattle.gov/portal/customize/LinkToRecord.aspx?altId=3001776-LU

# If you look at that webpage, you'll see that the text "Number of Curb Cuts for This Permit: "
# is within "span" tags
curbcuttext = soup.find("span", string="Number of Curb Cuts for This Permit: ")

# So to get the number of curb cuts (which is the next piece of text), 
# you can ask for the NEXT tag using find_next()

#.find_next() は BeautifulSoup における便利なメソッドの1つで、HTMLの中で「現在の要素のすぐ後ろにある要素を探す」ときに使う
#
n_curbcuts = curbcuttext.find_next()

# you'll need to add an if statement to deal with the case when this text does not exist

# your code here

AttributeError: 'NoneType' object has no attribute 'find_next'

In [82]:
curbcuttext = soup.find("span", string="Number of Curb Cuts for This Permit: ")

In [83]:
print(curbcuttext)

None

In [84]:
import numpy as np

if curbcuttext is None:
    n_curbcuts = np.nan
else:
    n_curbcuts = curbcuttext.find_next()

print(n_curbcuts)

nan

<div class="alert alert-block alert-info">
<strong>Exercise:</strong> Now turn that into a function that you can apply to each row of your dataframe. Add a new column, <strong>n_curbcuts</strong>, to your dataframe.
</div>

In [85]:
df.columns

Index(['permitnum', 'permitclass', 'permitclassmapped', 'permittypemapped',
       'description', 'statuscurrent', 'originaladdress1', 'originalcity',
       'originalstate', 'originalzip', 'link', 'latitude', 'longitude',
       'location1', 'housingunitsremoved', 'housingunitsadded', 'applieddate',
       'issueddate', 'expiresdate', 'decisiondate', 'permittypedesc',
       'contractorcompanyname', 'estprojectcost'],
      dtype='object')

In [86]:
print(df['link'])

0    {'url': 'https://services.seattle.gov/portal/c...
1    {'url': 'https://services.seattle.gov/portal/c...
2    {'url': 'https://services.seattle.gov/portal/c...
3    {'url': 'https://services.seattle.gov/portal/c...
4    {'url': 'https://services.seattle.gov/portal/c...
5    {'url': 'https://services.seattle.gov/portal/c...
6    {'url': 'https://services.seattle.gov/portal/c...
7    {'url': 'https://services.seattle.gov/portal/c...
Name: link, dtype: object

In [87]:
def curbcuts(x):
    permiturl = x['url']
    r = requests.get(permiturl)
    soup = BeautifulSoup(r.text)
    
    curbcuttext = soup.find("span", string="Number of Curb Cuts for This Permit: ")
    if curbcuttext is None:
        n_curbcuts = np.nan
    else:
        n_curbcuts = int(curbcuttext.find_next().text)
            
df['n_curbcuts'] = df['link'].apply(curbcuts)

In [88]:
df.head(8)

,permitnum,permitclass,permitclassmapped,permittypemapped,description,statuscurrent,originaladdress1,originalcity,originalstate,originalzip,...,housingunitsremoved,housingunitsadded,applieddate,issueddate,expiresdate,decisiondate,permittypedesc,contractorcompanyname,estprojectcost,n_curbcuts
0,3001212-LU,Single Family/Duplex,Residential,Master Use Permit,PROJECT CANCELLED 12/8/2010 -- This short plat...,Canceled,6519 S BANGOR ST,SEATTLE,WA,98178,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1,3001271-LU,Single Family/Duplex,Residential,Master Use Permit,Land Use Permit to adjust the boundary between...,Completed,4226 1ST AVE NW,SEATTLE,WA,98107,...,0.0,0.0,2005-12-16,2006-05-15,2007-11-15,2006-05-10,NaN,NaN,NaN,None
2,3001310-LU,Single Family/Duplex,Residential,Master Use Permit,Land use application to adjust the boundary be...,Completed,941 23RD AVE S,SEATTLE,WA,98144,...,NaN,NaN,2007-02-14,2008-08-28,2011-08-14,2008-08-13,NaN,NaN,NaN,None
3,3001312-LU,N/A,N/A,Master Use Permit,Cancelled due to no activity for more than 9 y...,Canceled,3131 E MADISON ST,SEATTLE,WA,98112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,3001440-LU,Commercial,Non-Residential,Master Use Permit,PROJECT CANCELLED 5/23/2011 -- Project On Hold...,Canceled,9030 13TH AVE NW,SEATTLE,WA,98117,...,NaN,NaN,2005-08-12,NaN,NaN,NaN,NaN,NaN,NaN,None
5,3001442-LU,Single Family/Duplex,Residential,Master Use Permit,Land Use Permit to subdivde two parcels into t...,Completed,7960 46TH AVE S,SEATTLE,WA,98118,...,0.0,0.0,2005-10-26,2007-04-23,2009-08-24,2006-04-27,NaN,NaN,NaN,None
6,3001452-LU,Multifamily,Residential,Master Use Permit,Land use permit to subdivide 1 parcel into 6 u...,Completed,4017 SW ADMIRAL WAY,SEATTLE,WA,NaN,...,NaN,NaN,2005-12-02,2006-05-26,2007-11-26,2006-04-04,NaN,NaN,NaN,None
7,3001610-LU,Multifamily,Residential,Master Use Permit,Land Use Application to subdivide one developm...,Completed,918 2ND AVE W,SEATTLE,WA,98119,...,NaN,NaN,2005-12-14,2012-07-12,2015-02-28,2012-02-15,NaN,NaN,NaN,None

In [ ]:


url = 'https://data.seattle.gov/resource/ht3q-kdvx.json' # copied and pasted from the webpage
r = requests.get(url)
df = pd.DataFrame(json.loads(r.text))

df = df.head(8) # get the first 5 rows, so we don't overload the city's website.

# get an example link
permiturl = df.loc[7,'link']['url']
print(permiturl)

# request that page and get the soup object
r = requests.get(permiturl)
soup = BeautifulSoup(r.text)
print(soup.prettify())

In [10]:
# your code here

def curbcut_count(soup):
    curbcuttext = soup.find("span", string="Number of Curb Cuts for This Permit: ")

    if curbcuttext is not None:
        n_curbcuts_tag = curbcuttext.find_next()
        if n_curbcuts_tag is not None:
            n_curbcuts = n_curbcuts_tag.text
        else:
            n_curbcuts = None
    else:
        n_curbcuts = None

df['n_curbcuts'] = df.apply(curbcut_count)

AttributeError: 'Series' object has no attribute 'find'

### Fixing errors
We'll do more scraping in just a moment. But first, let's do some examples of how to interpret an error message, and fix it.

<div class="alert alert-block alert-info">
<strong>Exercise:</strong> Each of the cells below will generate an error. Look at the error message and see if you can figure out how to fix it. (Don't Google it until you try to figure it out based on the error message.)
</div>

In [89]:
print(df.housingunitsadded)
print(df.housingunitsremoved)

0    NaN
1    0.0
2    NaN
3    NaN
4    NaN
5    0.0
6    NaN
7    NaN
Name: housingunitsadded, dtype: object
0    NaN
1    0.0
2    NaN
3    NaN
4    NaN
5    0.0
6    NaN
7    NaN
Name: housingunitsremoved, dtype: object

In [92]:
#もともとNaNを含むstrで、intに変えてもいいかと思ったけど、intはNaNを許容できない
#一方でfloatはNaNを許容できる
df['housingunitsadded'] = df.housingunitsadded.astype(float)
df['housingunitsremoved'] = df.housingunitsremoved.astype(float)

In [95]:
# the housingunitsremoved and housingunitsadded give useful information
# let's create a new column with netunits
df['netunits'] = df.housingunitsadded - df.housingunitsremoved
print(df.netunits)

0    NaN
1    0.0
2    NaN
3    NaN
4    NaN
5    0.0
6    NaN
7    NaN
Name: netunits, dtype: float64

In [102]:
df[['housingunitsadded','housingunitsremoved','netunits']].head(50)
#なぜここで[]を2つ用意しないといけない？

#[]を2回使うのは、「列名リストを渡すため」に必要だから
#外側の [] は「列を指定する操作」、内側の [] は 列名のリスト（複数形）
#df['netunits']だと、Series（1次元） だが、
#df[['housingunitsadded', 'housingunitsremoved', 'netunits']]はDataFrame（2次元）

   housingunitsadded  housingunitsremoved  netunits
0                NaN                  NaN       NaN
1                0.0                  0.0       0.0
2                NaN                  NaN       NaN
3                NaN                  NaN       NaN
4                NaN                  NaN       NaN
5                0.0                  0.0       0.0
6                NaN                  NaN       NaN
7                NaN                  NaN       NaN

In [97]:
# original prompt
# print the address of the first row
print('Address of first row is {}. Permit type is {}'.format(df.iloc[0].originaladdress1))

IndexError: Replacement index 1 out of range for positional args tuple

In [98]:
# print the address of the first row
print('Address of first row is {}. Permit type is {}'.format(df.iloc[0].originaladdress1, df.iloc[0].permittypemapped))

Address of first row is 6519 S BANGOR ST. Permit type is Master Use Permit

In [26]:
# original
# Convert the number of housing units to integers
# and then summarize

df['unitsadded_numeric'] = df.housingunitsadded.astype(int)
df.unitsadded_numeric.describe(

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [99]:
# original
# Convert the number of housing units to integers
# and then summarize

df['unitsadded_numeric'] = df.housingunitsadded.astype(float)
df.unitsadded_numeric.describe()

count    2.0
mean     0.0
std      0.0
min      0.0
25%      0.0
50%      0.0
75%      0.0
max      0.0
Name: unitsadded_numeric, dtype: float64

### Scraping craigslist

In the lecture, we saw how to scrape the main page (the list of posts).

What if you want to get more information about (say) a particular apartment?

Go to the [craigslist housing page](https://losangeles.craigslist.org/search/apa#search=1~gallery~0~0) and copy the link for one of the listings. It should look something like this:
https://losangeles.craigslist.org/lgb/apa/d/long-beach-home-for-rent/7597309102.html

(It's fine to copy and paste the URL for now. A second step would be to loop over the URLs from the dataframe of postings that we created in the video lecture, but in class, we'll just focus on one example.)

<div class="alert alert-block alert-info">
<strong>Exercise:</strong> For this URL, use requests to get the content of the post. (No need to create a soup object yet.)
</div>

In [104]:
import json
import requests
import pandas as pd
from bs4 import BeautifulSoup

# your code here
# put the output of the request in a variable called r
url = 'https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html' # copied and pasted from the webpage
r = requests.get(url)

# so you can access the content like this
print(r.content)

b'<!DOCTYPE html>\n<html>\n<head>\n    \n\t<meta charset="UTF-8">\n\t<meta http-equiv="X-UA-Compatible" content="IE=Edge">\n\t<meta name="viewport" content="width=device-width,initial-scale=1">\n\t<meta property="og:site_name" content="craigslist">\n\t<meta name="twitter:card" content="preview">\n\t<meta property="og:title" content="Sparkling Pool, Gated Community, Internet Access - apts/housing for rent - apartment rent - craigslist">\n\t<meta name="description" content="5825 Reseda Blvd, Tarzana, CA 91356 With its lush landscape, Tarzana Springs is the home you&#39;ve been looking for. Our beautiful one- and two-bedroom units are perfect for you and your family, with...">\n\t<meta property="og:description" content="5825 Reseda Blvd, Tarzana, CA 91356 With its lush landscape, Tarzana Springs is the home you&#39;ve been looking for. Our beautiful one- and two-bedroom units are perfect for you and your family, with...">\n\t<meta property="og:image" content="https://images.craigslist.org/00X0X_aOCL2zverPC_0uY0hq_600x450.jpg">\n\t<meta property="og:url" content="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html">\n\t<meta property="og:type" content="article">\n\t<meta name="robots" content="unavailable_after: 2025-05-16T06:57:28Z">\n\t<meta name="geo.position" content="34.167100;-118.541400">\n\t<meta name="ICBM" content="34.167100, -118.541400">\n\t<meta name="geo.placename" content="Tarzana">\n\t<meta name="geo.region" content="US-CA">\n\t<title>Sparkling Pool, Gated Community, Internet Access - apts/housing for rent - apartment rent - craigslist</title>\n\t<link rel="canonical" href="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html">\n\t<link rel="alternate" href="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html" hreflang="x-default">\n\n\n\n    <link rel="icon" href="/favicon.ico" id="favicon" />\n\n<script type="application/ld+json" id="ld_breadcrumb_data" >\n    {"itemListElement":[{"name":"losangeles.craigslist.org","position":1,"item":"https://losangeles.craigslist.org","@type":"ListItem"},{"name":"SF valley","position":2,"item":"https://losangeles.craigslist.org/sfv/","@type":"ListItem"},{"name":"housing","position":3,"@type":"ListItem","item":"https://losangeles.craigslist.org/search/sfv/hhh"},{"item":"https://losangeles.craigslist.org/search/sfv/apa","@type":"ListItem","position":4,"name":"apartments / housing for rent"},{"@type":"ListItem","item":"https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html","name":"Sparkling Pool, Gated Community, Internet Access","position":5}],"@type":"BreadcrumbList","@context":"https://schema.org"}\n</script>\n\n<script type="application/ld+json" id="ld_posting_data" >\n    {"numberOfBathroomsTotal":1,"name":"Sparkling Pool, Gated Community, Internet Access","address":{"@type":"PostalAddress","addressCountry":"US","postalCode":"91357","streetAddress":"5825 Reseda Blvd","addressLocality":"Tarzana","addressRegion":"CA"},"@type":"Apartment","latitude":"34.167100","longitude":"-118.541400","numberOfBedrooms":"1","petsAllowed":true,"@context":"http://schema.org"}\n</script>\n\n\n    <style>\n        body {\n            font-family: sans-serif;\n        }\n\n        #no-js {\n            position: fixed;\n            z-index: 100000;\n            top: 0;\n            bottom: 0;\n            left: 0;\n            right: 0;\n            overflow:auto;\n            margin: 0;\n            background: transparent;\n        }\n\n        #no-js h1 {\n            margin: 0;\n            padding: .5em;\n            color: #00E;\n            background-color: #cccccc;\n        }\n\n        #no-js  p {\n            margin: 1em;\n        }\n\n        .no-js header,\n        .no-js form,\n        .no-js .tsb,\n        .unsupported-browser header,\n        .unsupported-browser form,\n        .unsupported-browser .tsb {\n            display: none;\n        }\n\n        #curtain {\n            display: none;\n            position: fixed;\n            z-index: 9000;\n            top: 0;\n            bottom: 0;\n            left: 0;\n            right: 0;\n            margin: 0;\n            padding: 0;\n            border: 0;\n            background: transparent;\n        }\n\n        .show-curtain #curtain {\n            display: block;\n        }\n\n        #curtain .cover,\n        #curtain .content {\n            position: absolute;\n            display: block;\n            top: 0;\n            bottom: 0;\n            left: 0;\n            right: 0;\n            margin: 0;\n            padding: 0;\n            border: 0;\n        }\n\n        #curtain .cover {\n            z-index: 1;\n            background-color: white;\n        }\n\n        .show-curtain #curtain .cover {\n            opacity: 0.7;\n        }\n\n        .show-curtain.clear #curtain .cover {\n            opacity: 0;\n        }\n\n        .show-curtain.opaque #curtain .cover {\n            opacity: 1;\n        }\n\n        #curtain .content {\n            z-index: 2;\n            background: transparent;\n            color: #00E;\n\n            display: flex;\n            flex-direction: column;\n            justify-content: center;\n            align-items: center;\n        }\n\n        .unrecoverable #curtain .content,\n        .unsupported-browser #curtain .content {\n            display: block;\n            align-items: start;\n        }\n\n        #curtain h1 {\n            margin: 0;\n            padding: .5em;\n            background-color: #cccccc;\n        }\n\n        #curtain  p {\n            margin: 1em;\n            color: black;\n        }\n\n        .pacify #curtain .icom-:after {\n            content: "\\eb23";\n        }\n\n        #curtain .text {\n            display: none;\n        }\n\n        .loading #curtain .text.loading,\n        .reading #curtain .text.reading,\n        .writing #curtain .text.writing,\n        .saving #curtain .text.saving,\n        .searching #curtain .text.searching,\n        .unrecoverable #curtain .text.unrecoverable,\n        .message #curtain .text.message {\n            display: block;\n        }\n\n        .unrecoverable #curtain .text.unrecoverable {\n        }\n\n        @keyframes rotate {\n            from {\n                transform: rotate(0deg);\n            }\n            to {\n                transform: rotate(359deg);\n            }\n        }\n\n        .pacify #curtain .icom- {\n            font-size: 3em;\n            animation: rotate 2s infinite linear;\n        }\n    </style>\n\n\n    \n     \n     <script src="https://www.craigslist.org/static/www/59219857f2acaf38f9f5507d73c66d097cefa075.js" crossorigin="anonymous"></script>\n     <script>\n         window.cl.init(\n             \'https://www.craigslist.org/static/www/\',\n             \'\',\n             \'www\',\n             \'posting\',\n             {\n\'countOfTotalText\': "image {count} of {total}",\n\'defaultLocale\': "en_US",\n\'imageConfig\': {"4":{"hostname":"https://images.craigslist.org","sizes":["50x50c","300x300","600x450","1200x900"]},"0":{"hostname":"https://images.craigslist.org","sizes":["50x50c","300x300","600x450"]},"1":{"hostname":"https://images.craigslist.org","sizes":["50x50c","300x300","600x450","1200x900"]},"2":{"hostname":"https://images.craigslist.org","sizes":["50x50c","300x300","600x450","1200x900"]},"3":{"hostname":"https://images.craigslist.org","sizes":["50x50c","300x300","600x450","1200x900"]}},\n\'maptileBaseUrl\': "//map{s}.craigslist.org/t09/{z}/{x}/{y}.png",\n\'pID\': 7833430617\n},\n             0\n         );\n     </script>\n     \n\n    <script>\n        window.cl.specialCurtainMessages = {\n            unsupportedBrowser: [\n                "We\'ve detected you are using a browser that is missing critical features.",\n                "Please visit craigslist from a modern browser."\n            ],\n            unrecoverableError: [\n                "There was an error loading the page."\n            ]\n        };\n    </script>\n</head>\n\n<body  class="no-js show-curtain opaque posting"  >\n\n    \n    <iframe id="cl-local-storage" src="https://www.craigslist.org/static/www/localStorage-092e9f9e2f09450529e744902aa7cdb3a5cc868d.html" style="display:none;"></iframe>\n    \n\n\n    <section class="page-container">\n        <div class="bglogo"></div>\n<header class="global-header wide">\n   <a class="header-logo" name="logoLink" href="/">CL</a>\n\n    <nav class="breadcrumbs-container">\n<ul class="breadcrumbs">\n        <li class="crumb area">\n            <p>\n                    <a href="/">los angeles</a>\n\n                    <span class="breadcrumb-arrow">&gt;</span>\n            </p>\n        </li>\n\n        <li class="crumb subarea">\n            <p>\n                    <a href="/sfv/">SF valley</a>\n                    <span class="breadcrumb-arrow">&gt;</span>\n            </p>\n        </li>\n\n        <li class="crumb section">\n            <p>\n                        <a href="/search/sfv/hhh">housing </a>\n\n                    <span class="breadcrumb-arrow">&gt;</span>\n            </p>\n        </li>\n\n        <li class="crumb category">\n            <p>\n                <a href="/search/sfv/apa">apartments / housing for rent</a>\n\n            </p>\n        </li>\n\n</ul>\n    </nav>\n\n<div class="userlinks">\n    <ul class="user-actions">\n        <li class="user post">\n            <a href="https://post.craigslist.org/c/lax">post</a>\n        </li>\n        <li class="user account">\n            <a href="https://accounts.craigslist.org/login/home">account</a>\n        </li>\n    </ul>\n    <ul class="user-favs-discards">\n        <li class="user">\n            <div class="favorites">\n                <a href="#" class="favlink"><span class="icon icon-star fav" aria-hidden="true"></span><span class="fav-number"></span><span class="fav-label"> favorites</span></a>\n            </div>\n        </li>\n        <li class="user discards">\n            <div class="to-banish-page">\n                <a href="#" class="to-banish-page-link">\n                    <span class="icon icon-trash red" aria-hidden="true"></span>\n                    <span class="banished_count"></span>\n                    <span class="discards-label"> hidden</span>\n                </a>\n            </div>\n        </li>\n    </ul>\n</div>\n\n</header>\n<header class="global-header narrow">\n   <a class="header-logo" href="/">CL</a>\n    <nav class="breadcrumbs-container">\n\n    <div class="breadcrumbs">\n\nSF valley            &gt;\n\napartments / housing for rent    </div>\n\n\n    </nav>\n    <span class="linklike show-wide-header">...</span>\n</header>\n        <section class="body">\n<header class="dateReplyBar">\n    <div class="prevnext-sec">\n        <div class="prevnext js-only">\n    <a class="prev">&#9664;  prev </a>\n    <a class="backup" title="back to search">&#9650;</a>\n    <a class="next"> next &#9654; </a>\n</div>\n\n    </div>\n\n    <div class="reply-button-row">\n    <div class="actions-combo">\n    <button role="button" class="reply-button js-only" data-href="/reply/lax/apa/7833430617/__SERVICE_ID__">\n      reply\n    </button>\n\n      <div class="reply-info js-only"></div>\n    <div class="fave-unfave action">\n        <div class="fave" role="button"  title="add to favorites">\n            <div class="icon icon-star" aria-hidden="true"></div>\n            <div class="action-label">favorite</div>\n        </div>\n        <div class="unfave" role="button" title="remove from favorites">\n            <div class="icon icon-star fav" aria-hidden="true"></div>\n            <div class="action-label">favorite</div>\n        </div>\n    </div>\n<div class="banish-unbanish action">\n  <div class="banish" data-url="https://post.craigslist.org/flag" role="button"  title="hide this posting">\n    <div class="icon icon-trash" aria-hidden="true"></div>\n    <div class="action-label">hide</div>\n  </div>\n  <div class="unbanish" data-url="https://post.craigslist.org/flag" role="button"  title="restore this posting">\n    <div class="icon icon-trash red" aria-hidden="true"></div>\n    <div class="action-label">unhide</div>\n  </div>\n</div>\n    <div class="flag-action action">\n        <div class="flag" data-url="https://post.craigslist.org/flag" role="button" title="flag as prohibited / spam / miscategorized" >\n            <div class="flagIcon" aria-hidden="true">\n                <span class="white-flag">&#9872;</span>\n                <span class="black-flag">&#9873;</span>\n            </div>\n            <div class="action-label">\n                flag\n            </div>\n        </div>\n        <div class="unflag">\n            <div class="flagIcon" aria-hidden="true">&#9873;</div>\n            <a class="action-label" href="https://www.craigslist.org/about/help/faqs/flagging" title="thanks for flagging!">\n                flagged\n            </a>\n        </div>\n    </div>\n    <div class="action share-action">\n        <div class="share" id="sharebutton-container" ></div>\n    </div>\n    </div>\n\n            <p id="display-date" class="postinginfo reveal">\n                    Posted\n                    <time class="date timeago" datetime="2025-03-10T11:46:24-0700">\n                        2025-03-10 11:46\n                    </time>\n            </p>\n\n            <p class="print-information print-contact">\n                Contact Information: <span class="print-email"></span> <span class="print-phone"></span>\n            </p>\n            <a href="#" id="printme">print</a>\n\n    </div>\n\n</header>\n\n<h1 class="postingtitle">\n    <span class="postingtitletext">\n<span class="price">$2,233</span> <span class="housing">/ 1br - 770ft<sup>2</sup> - </span><span id="titletextonly">Sparkling Pool, Gated Community, Internet Access</span>    </span>\n</h1>\n    <h2 class="street-address">5825 Reseda Blvd, Tarzana, CA 91356</h2>\n<section class="userbody">\n    <figure class="iw multiimage">\n    <div class="gallery">\n        <span class="slider-back arrow">&lsaquo;</span>\n        <span class="slider-info">image 1 of 13</span>\n        <span class="slider-forward arrow">&rsaquo;</span>\n\n        <div class="swipe">\n            <div class="swipe-wrap">\n                <div id="1_image_aOCL2zverPC_0uY0hq" data-imgid="aOCL2zverPC_0uY0hq" class="slide first visible">\n                    <img src="https://images.craigslist.org/00X0X_aOCL2zverPC_0uY0hq_600x450.jpg" title="1" onerror="this.onerror = null; this.style.width=\'650px\'; this.style.height=\'400px\'; this.src=\'/images/no_image.png\'" alt="Sparkling Pool, Gated Community, Internet Access 1">\n                </div>\n                <div id="2_image_kzO9urzXGYM_0q70hq" data-imgid="kzO9urzXGYM_0q70hq" class="slide">\n                </div>\n                <div id="3_image_7grruc0bDM9_0q70hq" data-imgid="7grruc0bDM9_0q70hq" class="slide">\n                </div>\n                <div id="4_image_37cVcNLKRGr_0q70hq" data-imgid="37cVcNLKRGr_0q70hq" class="slide">\n                </div>\n                <div id="5_image_4oU4RGtHoZR_0bi0bi" data-imgid="4oU4RGtHoZR_0bi0bi" class="slide">\n                </div>\n                <div id="6_image_4QRSgh2dkUw_07K0ak" data-imgid="4QRSgh2dkUw_07K0ak" class="slide">\n                </div>\n                <div id="7_image_j6CBLamaE5l_07K0ak" data-imgid="j6CBLamaE5l_07K0ak" class="slide">\n                </div>\n                <div id="8_image_4umFkMS0XC6_07K0ak" data-imgid="4umFkMS0XC6_07K0ak" class="slide">\n                </div>\n                <div id="9_image_5D9v6paEOYu_07K0ak" data-imgid="5D9v6paEOYu_07K0ak" class="slide">\n                </div>\n                <div id="10_image_eZnrnFO0xRd_07K0ak" data-imgid="eZnrnFO0xRd_07K0ak" class="slide">\n                </div>\n                <div id="11_image_k7TKPXRpzjg_07K0ak" data-imgid="k7TKPXRpzjg_07K0ak" class="slide">\n                </div>\n                <div id="12_image_gFWFRdQoQHE_07K0ak" data-imgid="gFWFRdQoQHE_07K0ak" class="slide">\n                </div>\n                <div id="13_image_4bcWeOOPt8T_07K0ak" data-imgid="4bcWeOOPt8T_07K0ak" class="slide">\n                </div>\n            </div>\n        </div>\n    </div>\n    <div id="thumbs"><a id="1_thumb_aOCL2zverPC_0uY0hq" class="thumb" data-imgid="aOCL2zverPC_0uY0hq" href="https://images.craigslist.org/00X0X_aOCL2zverPC_0uY0hq_600x450.jpg" title="1"><img src="https://images.craigslist.org/00X0X_aOCL2zverPC_0uY0hq_50x50c.jpg" class="selected" alt="Sparkling Pool, Gated Community, Internet Access 1 thumbnail" onerror="this.onerror = null; this.src=\'/images/no_image.png\'"></a><a id="2_thumb_kzO9urzXGYM_0q70hq" class="thumb" data-imgid="kzO9urzXGYM_0q70hq" href="https://images.craigslist.org/00404_kzO9urzXGYM_0q70hq_600x450.jpg" title="2"><img src="https://images.craigslist.org/00404_kzO9urzXGYM_0q70hq_50x50c.jpg" alt="Sparkling Pool, Gated Community, Internet Access 2 thumbnail" onerror="this.onerror = null; this.src=\'/images/no_image.png\'"></a><a id="3_thumb_7grruc0bDM9_0q70hq" class="thumb" data-imgid="7grruc0bDM9_0q70hq" href="https://images.craigslist.org/00000_7grruc0bDM9_0q70hq_600x450.jpg" title="3"><img src="https://images.craigslist.org/00000_7grruc0bDM9_0q70hq_50x50c.jpg" alt="Sparkling Pool, Gated Community, Internet Access 3 thumbnail" onerror="this.onerror = null; this.src=\'/images/no_image.png\'"></a><a id="4_thumb_37cVcNLKRGr_0q70hq" class="thumb" data-imgid="37cVcNLKRGr_0q70hq" href="https://images.craigslist.org/00k0k_37cVcNLKRGr_0q70hq_600x450.jpg" title="4"><img src="https://images.craigslist.org/00k0k_37cVcNLKRGr_0q70hq_50x50c.jpg" alt="Sparkling Pool, Gated Community, Internet Access 4 thumbnail" onerror="this.onerror = null; this.src=\'/images/no_image.png\'"></a><a id="5_thumb_4oU4RGtHoZR_0bi0bi" class="thumb" data-imgid="4oU4RGtHoZR_0bi0bi" href="https://images.craigslist.org/00Q0Q_4oU4RGtHoZR_0bi0bi_600x450.jpg" title="5"><img src="https://images.craigslist.org/00Q0Q_4oU4RGtHoZR_0bi0bi_50x50c.jpg" alt="Sparkling Pool, Gated Community, Internet Access 5 thumbnail" onerror="this.onerror = null; this.src=\'/images/no_image.png\'"></a><a id="6_thumb_4QRSgh2dkUw_07K0ak" class="thumb" data-imgid="4QRSgh2dkUw_07K0ak" href="https://images.craigslist.org/00R0R_4QRSgh2dkUw_07K0ak_600x450.jpg" title="6"><img src="https://images.craigslist.org/00R0R_4QRSgh2dkUw_07K0ak_50x50c.jpg" alt="Sparkling Pool, Gated Community, Internet Access 6 thumbnail" onerror="this.onerror = null; this.src=\'/images/no_image.png\'"></a><a id="7_thumb_j6CBLamaE5l_07K0ak" class="thumb" data-imgid="j6CBLamaE5l_07K0ak" href="https://images.craigslist.org/00n0n_j6CBLamaE5l_07K0ak_600x450.jpg" title="7"><img src="https://images.craigslist.org/00n0n_j6CBLamaE5l_07K0ak_50x50c.jpg" alt="Sparkling Pool, Gated Community, Internet Access 7 thumbnail" onerror="this.onerror = null; this.src=\'/images/no_image.png\'"></a><a id="8_thumb_4umFkMS0XC6_07K0ak" class="thumb" data-imgid="4umFkMS0XC6_07K0ak" href="https://images.craigslist.org/00T0T_4umFkMS0XC6_07K0ak_600x450.jpg" title="8"><img src="https://images.craigslist.org/00T0T_4umFkMS0XC6_07K0ak_50x50c.jpg" alt="Sparkling Pool, Gated Community, Internet Access 8 thumbnail" onerror="this.onerror = null; this.src=\'/images/no_image.png\'"></a><a id="9_thumb_5D9v6paEOYu_07K0ak" class="thumb" data-imgid="5D9v6paEOYu_07K0ak" href="https://images.craigslist.org/00e0e_5D9v6paEOYu_07K0ak_600x450.jpg" title="9"><img src="https://images.craigslist.org/00e0e_5D9v6paEOYu_07K0ak_50x50c.jpg" alt="Sparkling Pool, Gated Community, Internet Access 9 thumbnail" onerror="this.onerror = null; this.src=\'/images/no_image.png\'"></a><a id="10_thumb_eZnrnFO0xRd_07K0ak" class="thumb" data-imgid="eZnrnFO0xRd_07K0ak" href="https://images.craigslist.org/00202_eZnrnFO0xRd_07K0ak_600x450.jpg" title="10"><img src="https://images

Now let's extract more information from the page. We have a couple of strategies here. First, we could skip trying to parse the page with `BeautifulSoup`, and just see if particular bits of text are present.

For example, what transportation modes does the post emphasize? Do they mention Section 8 vouchers? Some of this might be exploratory—we can see what type of language is included, and then parse in a more structured way (e.g. distinguishing between "No Section 8" and "Section 8 welcome").

<div class="alert alert-block alert-info">
    <strong>Exercise:</strong> Write a function that will return True if Section 8 is mentioned, otherwise False.

*Hint*: the `in` operator is a simple way to do this. For example:

In [105]:
'plan' in 'urban planning'

True

In [106]:
'plan' in 'Urban Planning'

False

In [107]:
import os
print(os.getcwd())

/Users/Tomo/Desktop/urbandatascience/classes_tomo

In [121]:
def checkSec8(url):
    r = requests.get(url)
    if "section 8" in r.text:
        return True
    else:
        return False

checkSec8(url)

False

In [108]:
#'data/cl_posts_ver1.html' というファイルを 読み込み専用（'r'） で開く
#with 文は、ファイルを開いて使い終わったあとに自動的に閉じてくれる安全な書き方
#fは開いたファイルを表すオブジェクト（ハンドル）。他の名前でもOK
with open('data/cl_posts_ver1.html', 'r') as f:

    #ファイルの中身をすべて読み取って、saved_content という変数に保存（中身はHTMLの文字列）
    saved_content = f.read() 

#BeautifulSoupライブラリを使ってHTMLの文字列（saved_content）を解析
#html.parser はPythonに内蔵されたHTMLパーサー
#HTMLパーサー（HTML parser）とは、HTML文書を「意味のある構造」として理解・処理できる形に変換するプログラムのこと
soup = BeautifulSoup(saved_content, features='html.parser')

#HTMLを インデント付きの見やすい形式 に整形して出力
print(soup.prettify())

<!DOCTYPE html>
<!-- saved from url=(0098)https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html -->
<html class="cl-not-small-viewport cl-landscape js canvas draggable fileAPI geolocation matchMedia picture pushState placeholder no-touchCapable transitions">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width,initial-scale=1" name="viewport"/>
  <meta content="craigslist" property="og:site_name"/>
  <meta content="preview" name="twitter:card"/>
  <meta content="Sparkling Pool, Gated Community, Internet Access - apts/housing for rent - apartment rent - craigslist" property="og:title"/>
  <meta content="5825 Reseda Blvd, Tarzana, CA 91356 With its lush landscape, Tarzana Springs is the home you've been looking for. Our beautiful one- and two-bedroom units are perfect for you and your family, with..." name="description"/>
  <meta content="5825 Reseda Blvd, Tarzana, CA 91356 With its lush landscape, Tarzana Springs is the home you've been looking for. Our beautiful one- and two-bedroom units are perfect for you and your family, with..." property="og:description"/>
  <meta content="https://images.craigslist.org/00X0X_aOCL2zverPC_0uY0hq_600x450.jpg" property="og:image"/>
  <meta content="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html" property="og:url"/>
  <meta content="article" property="og:type"/>
  <meta content="unavailable_after: 2025-05-16T06:57:28Z" name="robots"/>
  <meta content="34.167100;-118.541400" name="geo.position"/>
  <meta content="34.167100, -118.541400" name="ICBM"/>
  <meta content="Tarzana" name="geo.placename"/>
  <meta content="US-CA" name="geo.region"/>
  <title>
   Sparkling Pool, Gated Community, Internet Access - apts/housing for rent - apartment rent - craigslist
  </title>
  <link href="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html" rel="canonical"/>
  <link href="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html" hreflang="x-default" rel="alternate"/>
  <link href="https://losangeles.craigslist.org/favicon.ico" id="favicon" rel="icon"/>
  <script id="ld_breadcrumb_data" type="application/ld+json">
   {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"position":1,"@type":"ListItem","name":"losangeles.craigslist.org","item":"https://losangeles.craigslist.org"},{"name":"SF valley","item":"https://losangeles.craigslist.org/sfv/","position":2,"@type":"ListItem"},{"position":3,"@type":"ListItem","item":"https://losangeles.craigslist.org/search/sfv/hhh","name":"housing"},{"@type":"ListItem","position":4,"name":"apartments / housing for rent","item":"https://losangeles.craigslist.org/search/sfv/apa"},{"name":"Sparkling Pool, Gated Community, Internet Access","item":"https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html","position":5,"@type":"ListItem"}]}
  </script>
  <script id="ld_posting_data" type="application/ld+json">
   {"address":{"postalCode":"91357","addressRegion":"CA","streetAddress":"5825 Reseda Blvd","@type":"PostalAddress","addressCountry":"US","addressLocality":"Tarzana"},"name":"Sparkling Pool, Gated Community, Internet Access","latitude":"34.167100","numberOfBedrooms":"1","petsAllowed":true,"longitude":"-118.541400","numberOfBathroomsTotal":1,"@context":"http://schema.org","@type":"Apartment"}
  </script>
  <style>
   body {
            font-family: sans-serif;
        }

        #no-js {
            position: fixed;
            z-index: 100000;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            overflow:auto;
            margin: 0;
            background: transparent;
        }

        #no-js h1 {
            margin: 0;
            padding: .5em;
            color: #00E;
            background-color: #cccccc;
        }

        #no-js  p {
            margin: 1em;
        }

        .no-js header,
        .no-js form,
        .no-js .tsb,
        .unsupported-browser header,
        .unsupported-browser form,
        .unsupported-browser .tsb {
            display: none;
        }

        #curtain {
            display: none;
            position: fixed;
            z-index: 9000;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: 0;
            padding: 0;
            border: 0;
            background: transparent;
        }

        .show-curtain #curtain {
            display: block;
        }

        #curtain .cover,
        #curtain .content {
            position: absolute;
            display: block;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: 0;
            padding: 0;
            border: 0;
        }

        #curtain .cover {
            z-index: 1;
            background-color: white;
        }

        .show-curtain #curtain .cover {
            opacity: 0.7;
        }

        .show-curtain.clear #curtain .cover {
            opacity: 0;
        }

        .show-curtain.opaque #curtain .cover {
            opacity: 1;
        }

        #curtain .content {
            z-index: 2;
            background: transparent;
            color: #00E;

            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .unrecoverable #curtain .content,
        .unsupported-browser #curtain .content {
            display: block;
            align-items: start;
        }

        #curtain h1 {
            margin: 0;
            padding: .5em;
            background-color: #cccccc;
        }

        #curtain  p {
            margin: 1em;
            color: black;
        }

        .pacify #curtain .icom-:after {
            content: "\eb23";
        }

        #curtain .text {
            display: none;
        }

        .loading #curtain .text.loading,
        .reading #curtain .text.reading,
        .writing #curtain .text.writing,
        .saving #curtain .text.saving,
        .searching #curtain .text.searching,
        .unrecoverable #curtain .text.unrecoverable,
        .message #curtain .text.message {
            display: block;
        }

        .unrecoverable #curtain .text.unrecoverable {
        }

        @keyframes rotate {
            from {
                transform: rotate(0deg);
            }
            to {
                transform: rotate(359deg);
            }
        }

        .pacify #curtain .icom- {
            font-size: 3em;
            animation: rotate 2s infinite linear;
        }
  </style>
  <script crossorigin="anonymous" src="./Sparkling Pool, Gated Community, Internet Access - apts_housing for rent - apartment rent - craigslist_files/59219857f2acaf38f9f5507d73c66d097cefa075.js">
  </script>
  <script>
   window.cl.init(
             'https://www.craigslist.org/static/www/',
             '',
             'www',
             'posting',
             {
'countOfTotalText': "image {count} of {total}",
'defaultLocale': "en_US",
'imageConfig': {"2":{"hostname":"https://images.craigslist.org","sizes":["50x50c","300x300","600x450","1200x900"]},"3":{"hostname":"https://images.craigslist.org","sizes":["50x50c","300x300","600x450","1200x900"]},"0":{"sizes":["50x50c","300x300","600x450"],"hostname":"https://images.craigslist.org"},"1":{"sizes":["50x50c","300x300","600x450","1200x900"],"hostname":"https://images.craigslist.org"},"4":{"sizes":["50x50c","300x300","600x450","1200x900"],"hostname":"https://images.craigslist.org"}},
'maptileBaseUrl': "//map{s}.craigslist.org/t09/{z}/{x}/{y}.png",
'pID': 7833430617
},
             0
         );
  </script>
  <script>
   window.cl.specialCurtainMessages = {
            unsupportedBrowser: [
                "We've detected you are using a browser that is missing critical features.",
                "Please visit craigslist from a modern browser."
            ],
            unrecoverableError: [
                "There was an error loading the page."
            ]
        };
  </script>
  <script crossorigin="anonymous" src="./Sparkling Pool, Gated Community, Internet Access - apts_housing for rent - apartment rent - craigslist_files/manifest.js" type="text/javascript">
  </script>
  <link href="./Sparkling Pool, Gated Community, Internet Access - apts_housing for rent - apartment rent - craigslist_files/posting-2025-04-07-11-52-12d407f47894eee27ca4858934ba360997f218cd.css" rel="stylesheet" type="text/css"/>
  <script crossorigin="anonymous" src="./Sparkling Pool, Gated Community, Internet Access - apts_housing for rent - apartment rent - craigslist_files/browsePostings-2025-04-07-11-52-727c1a58578ff8e795f14b152bd72a7b6928221b.js" type="text/javascript">
  </script>
  <style>
  </style>
 </head>
 <body class="posting bd-can-hover desktop w1024" data-gr-ext-installed="" data-new-gr-c-s-check-loaded="14.1231.0">
  <iframe id="cl-local-storage" src="./Sparkling Pool, Gated Community, Internet Access - apts_housing for rent - apartment rent - craigslist_files/localStorage-092e9f9e2f09450529e744902aa7cdb3a5cc868d.html" style="display:none;">
  </iframe>
  <section class="page-container">
   <div class="bglogo">
   </div>
   <header class="global-header wide">
    <a class="header-logo" href="https://losangeles.craigslist.org/" name="logoLink">
     CL
    </a>
    <nav class="breadcrumbs-container">
     <ul class="breadcrumbs">
      <li class="crumb area">
       <p>
        <a href="https://losangeles.craigslist.org/">
         los angeles
        </a>
        <span class="breadcrumb-arrow">
         &gt;
        </span>
       </p>
      </li>
      <li class="crumb subarea">
       <p>
        <a href="https://losangeles.craigslist.org/sfv/">
         SF valley
        </a>
        <span class="breadcrumb-arrow">
         &gt;
        </span>
       </p>
      </li>
      <li class="crumb section">
       <p>
        <a href="https://losangeles.craigslist.org/search/sfv/hhh">
         housing
        </a>
        <span class="breadcrumb-arrow">
         &gt;
        </span>
       </p>
      </li>
      <li class="crumb category">
       <p>
        <a href="https://losangeles.craigslist.org/search/sfv/apa">
         apartments / housing for rent
        </a>
       </p>
      </li>
     </ul>
    </nav>
    <div class="userlinks">
     <ul class="user-actions">
      <li class="user post">
       <a href="https://post.craigslist.org/c/lax">
        post
       </a>
      </li>
      <li class="user account">
       <a href="https://accounts.craigslist.org/login/home">
        account
       </a>
      </li>
     </ul>
     <ul class="user-favs-discards">
      <li class="user">
       <div class="favorites off">
        <a class="favlink" href="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html#">
         <span aria-hidden="true" class="icon icon-star fav">
         </span>
         <span class="fav-number">
          0
         </span>
         <span class="fav-label">
          favorites
         </span>
        </a>
       </div>
      </li>
      <li class="user discards">
       <div class="to-banish-page">
        <a class="to-banish-page-link" href="https://losangeles.craigslist.org/favorites?uf=1&amp;fl=aXRlbXM6">
         <span aria-hidden="true" class="icon icon-trash red">
         </span>
         <span class="banished_count">
          0
         </span>
         <span class="discards-label">
          hidden
         </span>
        </a>
       </div>
      </li>
     </ul>
    </div>
   </header>
   <header class="global-header narrow">
    <a class="header-logo" href="https://losangeles.craigslist.org/">
     CL
    </a>
    <nav class="breadcrumbs-container">
     <div class="breadcrumbs">
      SF valley            &gt;

apartments / housing for rent
     </div>
    </nav>
    <span class="linklike show-wide-header">
     ...
    </span>
   </header>
   <section class="body">
    <header class="dateReplyBar">
     <div class="prevnext-sec">
      <div class="prevnext js-only show-prevnext">
       <a class="prev">
        ◀  prev
       </a>
       <a class="backup" href="https://losangeles.craigslist.org/search/apa#search=1~gallery~0~0~p7833430617" title="back to search">
        ▲
       </a>
       <a class="next" href="https://losangeles.craigslist.org/lac/apa/7839095586.html">
        next ▶
       </a>
      </div>
     </div>
     <div class="reply-button-row">
      <div class="actions-combo">
       <button class="reply-button js-only" data-href="/reply/lax/apa/7833430617/__SERVICE_ID__" role="button">
        reply
       </button>
       <div class="reply-info js-only">
       </div>
       <div class="fave-unfave action">
        <div class="fave" role="button" title="add to favorites">
         <div aria-hidden="true" class="icon icon-star">
         </div>
         <div class="action-label">
          favorite
         </div>
        </div>
        <div class="unfave" role="button" title="remove from favorites">
         <div aria-hidden="true" class="icon icon-star fav">
         </div>
         <div class="action-label">
          favorite
         </div>
        </div>
       </div>
       <div class="banish-unbanish action">
        <div class="banish" data-url="https://post.craigslist.org/flag" role="button" title="hide this posting">
         <div aria-hidden="true" class="icon icon-trash">
         </div>
         <div class="action-label">
          hide
         </div>
        </div>
        <div class="unbanish" data-url="https://post.craigslist.org/flag" role="button" title="restore this posting">
         <div aria-hidden="true" class="icon icon-trash red">
         </div>
         <div class="action-label">
          unhide
         </div>
        </div>
       </div>
       <div class="flag-action action">
        <div class="flag" data-url="https://post.craigslist.org/flag" role="button" title="flag as prohibited / spam / miscategorized">
         <div aria-hidden="true" class="flagIcon">
          <span class="white-flag">
           ⚐
          </span>
          <span class="black-flag">
           ⚑
          </span>
         </div>
         <div class="action-label">
          flag
         </div>
        </div>
        <div class="unflag">
         <div aria-hidden="true" class="flagIcon">
          ⚑
         </div>
         <a class="action-label" href="https://www.craigslist.org/about/help/faqs/flagging" title="thanks for flagging!">
          flagged
         </a>
        </div>
       </div>
       <div class="action share-action">
        <div class="share" id="sharebutton-container">
         <div class="cl-share-button">
          <div class="container">
           <a href="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html#share">
            <div class="icom- share-icon">
             
            </div>
            <span class="action-label">
             share
            </span>
           </a>
           <div class="menu-container">
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
      <p class="postinginfo reveal" id="display-date" style="opacity: 1;">
       Posted
       <time class="date timeago" datetime="2025-03-10T11:46:24-0700" title="2025-03-10 11:46">
        about a month ago
       </time>
      </p>
      <p class="print-information print-contact">
       Contact Information:
       <span class="print-email">
       </span>
       <span class="print-phone">
       </span>
      </p>
      <a href="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html#" id="printme">
       print
      </a>
     </div>
    </header>
    <h1 class="postingtitle">
     <span class="postingtitletext">
      <span class="price">
       $2,233
      </span>
      <span class="housing">
       / 1br - 770ft
       <sup>
        2
       </sup>
       -
      </span>
      <span id="titletextonly">
       Sparkling Pool, Gated Community, Internet Access
      </span>
     </span>
    </h1>
    <h2 class="street-address">
     5825 Reseda Blvd, Tarzana, CA 91356
    </h2>
    <section class="userbody">
     <figure class="iw multiimage">
      <div class="gallery">
       <span class="slider-back arrow">
        ‹
       </span>
       <span class="slider-info">
        image 1 of 13
       </span>
       <span class="slider-forward arrow">
        ›
       </span>
       <div class="swipe" style="visibility: visible;">
        <div class="swipe-wrap" style="width: 7800px;">
         <div class="slide first visible" data-imgid="aOCL2zverPC_0uY0hq" data-index="0" id="1_image_aOCL2zverPC_0uY0hq" style="width: 600px; left: 0px; transition-duration: 0ms; transform: translate(0px, 0px);">
          <img alt="Sparkling Pool, Gated Community, Internet Access 1" onerror="this.onerror = null; this.style.width='650px'; this.style.height='400px'; this.src='/images/no_image.png'" src="./Sparkling Pool, Gated Community, Internet Access - apts_housing for rent - apartment rent - craigslist_files/00X0X_aOCL2zverPC_0uY0hq_1200x900.jpg" title="1"/>
         </div>
         <div class="slide" data-imgid="kzO9urzXGYM_0q70hq" data-index="1" id="2_image_kzO9urzXGYM_0q70hq" style="width: 600px; left: -600px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="7grruc0bDM9_0q70hq" data-index="2" id="3_image_7grruc0bDM9_0q70hq" style="width: 600px; left: -1200px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="37cVcNLKRGr_0q70hq" data-index="3" id="4_image_37cVcNLKRGr_0q70hq" style="width: 600px; left: -1800px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="4oU4RGtHoZR_0bi0bi" data-index="4" id="5_image_4oU4RGtHoZR_0bi0bi" style="width: 600px; left: -2400px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="4QRSgh2dkUw_07K0ak" data-index="5" id="6_image_4QRSgh2dkUw_07K0ak" style="width: 600px; left: -3000px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="j6CBLamaE5l_07K0ak" data-index="6" id="7_image_j6CBLamaE5l_07K0ak" style="width: 600px; left: -3600px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="4umFkMS0XC6_07K0ak" data-index="7" id="8_image_4umFkMS0XC6_07K0ak" style="width: 600px; left: -4200px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="5D9v6paEOYu_07K0ak" data-index="8" id="9_image_5D9v6paEOYu_07K0ak" style="width: 600px; left: -4800px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="eZnrnFO0xRd_07K0ak" data-index="9" id="10_image_eZnrnFO0xRd_07K0ak" style="width: 600px; left: -5400px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="k7TKPXRpzjg_07K0ak" data-index="10" id="11_image_k7TKPXRpzjg_07K0ak" style="width: 600px; left: -6000px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>
         <div class="slide" data-imgid="gFWFRdQoQHE_07K0ak" data-index="11" id="12_image_gFWFRdQoQHE_07K0ak" style="width: 600px; left: -6600px; transition-duration: 0ms; transform: translate(600px, 0px);">
         </div>

In [109]:
# your code here to return Section 8 information

'Section 8' in soup

False

In [3]:
#r.textを使う場合と、BeautifulSoupを使う場合の違いとは？

#r.textを使う方法は、HTML全体を文字列として取得している。
#なので、特定の単語がページに含まれているかだけを見たいときに便利（構造は無視）。
#スクレイピングの前段階でのフィルター処理などに向いている。
#BeautifulSoupを使うと、構造を解析して検索しやすくなる。
#つまり、r.textは構造を無視してしまうが、BeautifulSoupはposts = soup.find_all('li', class_='cl-search-result’)のようにレイヤーを指定しての検索ができる。

#BeautifulSoupは、htmlファイルをダウンロードせずとも、下の構文のようにrequestsを使ってオンライン上の内容に直接使える
#lecture2cでBeautifulSoupをダウンロードデータに使っていたのは、Craigslistがrequestsを受け付けなくなっているから

url = 'https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html' # copied and pasted from the webpage
r = requests.get(url)
soup = BeautifulSoup(r.text, features='html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width,initial-scale=1" name="viewport"/>
  <meta content="craigslist" property="og:site_name"/>
  <meta content="preview" name="twitter:card"/>
  <meta content="Sparkling Pool, Gated Community, Internet Access - apts/housing for rent - apartment rent - craigslist" property="og:title"/>
  <meta content="5825 Reseda Blvd, Tarzana, CA 91356 With its lush landscape, Tarzana Springs is the home you've been looking for. Our beautiful one- and two-bedroom units are perfect for you and your family, with..." name="description"/>
  <meta content="5825 Reseda Blvd, Tarzana, CA 91356 With its lush landscape, Tarzana Springs is the home you've been looking for. Our beautiful one- and two-bedroom units are perfect for you and your family, with..." property="og:description"/>
  <meta content="https://images.craigslist.org/00X0X_aOCL2zverPC_0uY0hq_600x450.jpg" property="og:image"/>
  <meta content="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html" property="og:url"/>
  <meta content="article" property="og:type"/>
  <meta content="unavailable_after: 2025-05-16T06:57:28Z" name="robots"/>
  <meta content="34.167100;-118.541400" name="geo.position"/>
  <meta content="34.167100, -118.541400" name="ICBM"/>
  <meta content="Tarzana" name="geo.placename"/>
  <meta content="US-CA" name="geo.region"/>
  <title>
   Sparkling Pool, Gated Community, Internet Access - apts/housing for rent - apartment rent - craigslist
  </title>
  <link href="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html" rel="canonical"/>
  <link href="https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html" hreflang="x-default" rel="alternate"/>
  <link href="/favicon.ico" id="favicon" rel="icon">
   <script id="ld_breadcrumb_data" type="application/ld+json">
    {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"item":"https://losangeles.craigslist.org","position":1,"name":"losangeles.craigslist.org","@type":"ListItem"},{"position":2,"item":"https://losangeles.craigslist.org/sfv/","name":"SF valley","@type":"ListItem"},{"name":"housing","position":3,"item":"https://losangeles.craigslist.org/search/sfv/hhh","@type":"ListItem"},{"@type":"ListItem","name":"apartments / housing for rent","position":4,"item":"https://losangeles.craigslist.org/search/sfv/apa"},{"name":"Sparkling Pool, Gated Community, Internet Access","position":5,"item":"https://losangeles.craigslist.org/sfv/apa/d/tarzana-sparkling-pool-gated-community/7833430617.html","@type":"ListItem"}]}
   </script>
   <script id="ld_posting_data" type="application/ld+json">
    {"address":{"streetAddress":"5825 Reseda Blvd","addressCountry":"US","addressRegion":"CA","postalCode":"91357","@type":"PostalAddress","addressLocality":"Tarzana"},"@type":"Apartment","@context":"http://schema.org","name":"Sparkling Pool, Gated Community, Internet Access","numberOfBathroomsTotal":1,"numberOfBedrooms":"1","latitude":"34.167100","petsAllowed":true,"longitude":"-118.541400"}
   </script>
   <style>
    body {
            font-family: sans-serif;
        }

        #no-js {
            position: fixed;
            z-index: 100000;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            overflow:auto;
            margin: 0;
            background: transparent;
        }

        #no-js h1 {
            margin: 0;
            padding: .5em;
            color: #00E;
            background-color: #cccccc;
        }

        #no-js  p {
            margin: 1em;
        }

        .no-js header,
        .no-js form,
        .no-js .tsb,
        .unsupported-browser header,
        .unsupported-browser form,
        .unsupported-browser .tsb {
            display: none;
        }

        #curtain {
            display: none;
            position: fixed;
            z-index: 9000;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: 0;
            padding: 0;
            border: 0;
            background: transparent;
        }

        .show-curtain #curtain {
            display: block;
        }

        #curtain .cover,
        #curtain .content {
            position: absolute;
            display: block;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: 0;
            padding: 0;
            border: 0;
        }

        #curtain .cover {
            z-index: 1;
            background-color: white;
        }

        .show-curtain #curtain .cover {
            opacity: 0.7;
        }

        .show-curtain.clear #curtain .cover {
            opacity: 0;
        }

        .show-curtain.opaque #curtain .cover {
            opacity: 1;
        }

        #curtain .content {
            z-index: 2;
            background: transparent;
            color: #00E;

            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .unrecoverable #curtain .content,
        .unsupported-browser #curtain .content {
            display: block;
            align-items: start;
        }

        #curtain h1 {
            margin: 0;
            padding: .5em;
            background-color: #cccccc;
        }

        #curtain  p {
            margin: 1em;
            color: black;
        }

        .pacify #curtain .icom-:after {
            content: "\eb23";
        }

        #curtain .text {
            display: none;
        }

        .loading #curtain .text.loading,
        .reading #curtain .text.reading,
        .writing #curtain .text.writing,
        .saving #curtain .text.saving,
        .searching #curtain .text.searching,
        .unrecoverable #curtain .text.unrecoverable,
        .message #curtain .text.message {
            display: block;
        }

        .unrecoverable #curtain .text.unrecoverable {
        }

        @keyframes rotate {
            from {
                transform: rotate(0deg);
            }
            to {
                transform: rotate(359deg);
            }
        }

        .pacify #curtain .icom- {
            font-size: 3em;
            animation: rotate 2s infinite linear;
        }
   </style>
   <script crossorigin="anonymous" src="https://www.craigslist.org/static/www/59219857f2acaf38f9f5507d73c66d097cefa075.js">
   </script>
   <script>
    window.cl.init(
             'https://www.craigslist.org/static/www/',
             '',
             'www',
             'posting',
             {
'countOfTotalText': "image {count} of {total}",
'defaultLocale': "en_US",
'imageConfig': {"4":{"hostname":"https://images.craigslist.org","sizes":["50x50c","300x300","600x450","1200x900"]},"3":{"hostname":"https://images.craigslist.org","sizes":["50x50c","300x300","600x450","1200x900"]},"0":{"sizes":["50x50c","300x300","600x450"],"hostname":"https://images.craigslist.org"},"2":{"sizes":["50x50c","300x300","600x450","1200x900"],"hostname":"https://images.craigslist.org"},"1":{"sizes":["50x50c","300x300","600x450","1200x900"],"hostname":"https://images.craigslist.org"}},
'maptileBaseUrl': "//map{s}.craigslist.org/t09/{z}/{x}/{y}.png",
'pID': 7833430617
},
             0
         );
   </script>
   <script>
    window.cl.specialCurtainMessages = {
            unsupportedBrowser: [
                "We've detected you are using a browser that is missing critical features.",
                "Please visit craigslist from a modern browser."
            ],
            unrecoverableError: [
                "There was an error loading the page."
            ]
        };
   </script>
  </link>
 </head>
 <body class="no-js show-curtain opaque posting">
  <iframe id="cl-local-storage" src="https://www.craigslist.org/static/www/localStorage-092e9f9e2f09450529e744902aa7cdb3a5cc868d.html" style="display:none;">
  </iframe>
  <section class="page-container">
   <div class="bglogo">
   </div>
   <header class="global-header wide">
    <a class="header-logo" href="/" name="logoLink">
     CL
    </a>
    <nav class="breadcrumbs-container">
     <ul class="breadcrumbs">
      <li class="crumb area">
       <p>
        <a href="/">
         los angeles
        </a>
        <span class="breadcrumb-arrow">
         &gt;
        </span>
       </p>
      </li>
      <li class="crumb subarea">
       <p>
        <a href="/sfv/">
         SF valley
        </a>
        <span class="breadcrumb-arrow">
         &gt;
        </span>
       </p>
      </li>
      <li class="crumb section">
       <p>
        <a href="/search/sfv/hhh">
         housing
        </a>
        <span class="breadcrumb-arrow">
         &gt;
        </span>
       </p>
      </li>
      <li class="crumb category">
       <p>
        <a href="/search/sfv/apa">
         apartments / housing for rent
        </a>
       </p>
      </li>
     </ul>
    </nav>
    <div class="userlinks">
     <ul class="user-actions">
      <li class="user post">
       <a href="https://post.craigslist.org/c/lax">
        post
       </a>
      </li>
      <li class="user account">
       <a href="https://accounts.craigslist.org/login/home">
        account
       </a>
      </li>
     </ul>
     <ul class="user-favs-discards">
      <li class="user">
       <div class="favorites">
        <a class="favlink" href="#">
         <span aria-hidden="true" class="icon icon-star fav">
         </span>
         <span class="fav-number">
         </span>
         <span class="fav-label">
          favorites
         </span>
        </a>
       </div>
      </li>
      <li class="user discards">
       <div class="to-banish-page">
        <a class="to-banish-page-link" href="#">
         <span aria-hidden="true" class="icon icon-trash red">
         </span>
         <span class="banished_count">
         </span>
         <span class="discards-label">
          hidden
         </span>
        </a>
       </div>
      </li>
     </ul>
    </div>
   </header>
   <header class="global-header narrow">
    <a class="header-logo" href="/">
     CL
    </a>
    <nav class="breadcrumbs-container">
     <div class="breadcrumbs">
      SF valley            &gt;

apartments / housing for rent
     </div>
    </nav>
    <span class="linklike show-wide-header">
     ...
    </span>
   </header>
   <section class="body">
    <header class="dateReplyBar">
     <div class="prevnext-sec">
      <div class="prevnext js-only">
       <a class="prev">
        ◀  prev
       </a>
       <a class="backup" title="back to search">
        ▲
       </a>
       <a class="next">
        next ▶
       </a>
      </div>
     </div>
     <div class="reply-button-row">
      <div class="actions-combo">
       <button class="reply-button js-only" data-href="/reply/lax/apa/7833430617/__SERVICE_ID__" role="button">
        reply
       </button>
       <div class="reply-info js-only">
       </div>
       <div class="fave-unfave action">
        <div class="fave" role="button" title="add to favorites">
         <div aria-hidden="true" class="icon icon-star">
         </div>
         <div class="action-label">
          favorite
         </div>
        </div>
        <div class="unfave" role="button" title="remove from favorites">
         <div aria-hidden="true" class="icon icon-star fav">
         </div>
         <div class="action-label">
          favorite
         </div>
        </div>
       </div>
       <div class="banish-unbanish action">
        <div class="banish" data-url="https://post.craigslist.org/flag" role="button" title="hide this posting">
         <div aria-hidden="true" class="icon icon-trash">
         </div>
         <div class="action-label">
          hide
         </div>
        </div>
        <div class="unbanish" data-url="https://post.craigslist.org/flag" role="button" title="restore this posting">
         <div aria-hidden="true" class="icon icon-trash red">
         </div>
         <div class="action-label">
          unhide
         </div>
        </div>
       </div>
       <div class="flag-action action">
        <div class="flag" data-url="https://post.craigslist.org/flag" role="button" title="flag as prohibited / spam / miscategorized">
         <div aria-hidden="true" class="flagIcon">
          <span class="white-flag">
           ⚐
          </span>
          <span class="black-flag">
           ⚑
          </span>
         </div>
         <div class="action-label">
          flag
         </div>
        </div>
        <div class="unflag">
         <div aria-hidden="true" class="flagIcon">
          ⚑
         </div>
         <a class="action-label" href="https://www.craigslist.org/about/help/faqs/flagging" title="thanks for flagging!">
          flagged
         </a>
        </div>
       </div>
       <div class="action share-action">
        <div class="share" id="sharebutton-container">
        </div>
       </div>
      </div>
      <p class="postinginfo reveal" id="display-date">
       Posted
       <time class="date timeago" datetime="2025-03-10T11:46:24-0700">
        2025-03-10 11:46
       </time>
      </p>
      <p class="print-information print-contact">
       Contact Information:
       <span class="print-email">
       </span>
       <span class="print-phone">
       </span>
      </p>
      <a href="#" id="printme">
       print
      </a>
     </div>
    </header>
    <h1 class="postingtitle">
     <span class="postingtitletext">
      <span class="price">
       $2,233
      </span>
      <span class="housing">
       / 1br - 770ft
       <sup>
        2
       </sup>
       -
      </span>
      <span id="titletextonly">
       Sparkling Pool, Gated Community, Internet Access
      </span>
     </span>
    </h1>
    <h2 class="street-address">
     5825 Reseda Blvd, Tarzana, CA 91356
    </h2>
    <section class="userbody">
     <figure class="iw multiimage">
      <div class="gallery">
       <span class="slider-back arrow">
        ‹
       </span>
       <span class="slider-info">
        image 1 of 13
       </span>
       <span class="slider-forward arrow">
        ›
       </span>
       <div class="swipe">
        <div class="swipe-wrap">
         <div class="slide first visible" data-imgid="aOCL2zverPC_0uY0hq" id="1_image_aOCL2zverPC_0uY0hq">
          <img alt="Sparkling Pool, Gated Community, Internet Access 1" onerror="this.onerror = null; this.style.width='650px'; this.style.height='400px'; this.src='/images/no_image.png'" src="https://images.craigslist.org/00X0X_aOCL2zverPC_0uY0hq_600x450.jpg" title="1"/>
         </div>
         <div class="slide" data-imgid="kzO9urzXGYM_0q70hq" id="2_image_kzO9urzXGYM_0q70hq">
         </div>
         <div class="slide" data-imgid="7grruc0bDM9_0q70hq" id="3_image_7grruc0bDM9_0q70hq">
         </div>
         <div class="slide" data-imgid="37cVcNLKRGr_0q70hq" id="4_image_37cVcNLKRGr_0q70hq">
         </div>
         <div class="slide" data-imgid="4oU4RGtHoZR_0bi0bi" id="5_image_4oU4RGtHoZR_0bi0bi">
         </div>
         <div class="slide" data-imgid="4QRSgh2dkUw_07K0ak" id="6_image_4QRSgh2dkUw_07K0ak">
         </div>
         <div class="slide" data-imgid="j6CBLamaE5l_07K0ak" id="7_image_j6CBLamaE5l_07K0ak">
         </div>
         <div class="slide" data-imgid="4umFkMS0XC6_07K0ak" id="8_image_4umFkMS0XC6_07K0ak">
         </div>
         <div class="slide" data-imgid="5D9v6paEOYu_07K0ak" id="9_image_5D9v6paEOYu_07K0ak">
         </div>
         <div class="slide" data-imgid="eZnrnFO0xRd_07K0ak" id="10_image_eZnrnFO0xRd_07K0ak">
         </div>
         <div class="slide" data-imgid="k7TKPXRpzjg_07K0ak" id="11_image_k7TKPXRpzjg_07K0ak">
         </div>
         <div class="slide" data-imgid="gFWFRdQoQHE_07K0ak" id="12_image_gFWFRdQoQHE_07K0ak">
         </div>
         <div class="slide" data-imgid="4bcWeOOPt8T_07K0ak" id="13_image_4bcWeOOPt8T_07K0ak">
         </div>
        </div>
       </div>
      </div>
      <div id="thumbs">
       <a class="thumb" data-imgid="aOCL2zverPC_0uY0hq" href="https://images.craigslist.org/00X0X_aOCL2zverPC_0uY0hq_600x450.jpg" id="1_thumb_aOCL2zverPC_0uY0hq" title="1">
        <img alt="Sparkling Pool, Gated Community, Internet Access 1 thumbnail" class="selected" onerror="this.onerror = null; this.src='/images/no_image.png'" src="https://images.craigslist.org/00X0X_aOCL2zverPC_0uY0hq_50x50c.jpg"/>
       </a>
       <a class="thumb" data-imgid="kzO9urzXGYM_0q70hq" href="https://images.craigslist.org/00404_kzO9urzXGYM_0q70hq_600x450.jpg" id="2_thumb_kzO9urzXGYM_0q70hq" title="2">
        <img alt="Sparkling Pool, Gated Community, Internet Access 2 thumbnail" onerror="this.onerror = null; this.src='/images/no_image.png'" src="https://images.craigslist.org/00404_kzO9urzXGYM_0q70hq_50x50c.jpg"/>
       </a>
       <a class="thumb" data-imgid="7grruc0bDM9_0q70hq" href="https://images.craigslist.org/00000_7grruc0bDM9_0q70hq_600x450.jpg" id="3_thumb_7grruc0bDM9_0q70hq" title="3">
        <img alt="Sparkling Pool, Gated Community, Internet Access 3 thumbnail" onerror="this.onerror = null; this.src='/images/no_image.png'" src="https://images.craigslist.org/00000_7grruc0bDM9_0q70hq_50x50c.jpg"/>
       </a>
       <a class="thumb" data-imgid="37cVcNLKRGr_0q70hq" href="https://images.craigslist.org/00k0k_37cVcNLKRGr_0q70hq_600x450.jpg" id="4_thumb_37cVcNLKRGr_0q70hq" title="4">
        <img alt="Sparkling Pool, Gated Community, Internet Access 4 thumbnail" onerror="this.onerror = null; this.src='/images/no_image.png'" src="https://images.craigslist.org/00k0k_37cVcNLKRGr_0q70hq_50x50c.jpg"/>
       </a>
       <a class="thumb" data-imgid="4oU4RGtHoZR_0bi0bi" href="https://images.craigslist.org/00Q0Q_4oU4RGtHoZR_0bi0bi_600x450.jpg" id="5_thumb_4oU4RGtHoZR_0bi0bi" title="5">
        <img alt="Sparkling Pool, Gated Community, Internet Access 5 thumbnail" onerror="this.onerror = null; this.src='/images/no_image.png'" src="https://images.craigslist.org/00Q0Q_4oU4RGtHoZR_0bi0bi_50x50c.jpg"/>
       </a>
       <a class="thumb" data-imgid="4QRSgh2dkUw_07K0ak" href="https://images.craigslist.org/00R0R_4QRSgh2dkUw_07K0ak_600x450.jpg" id="6_thumb_4QRSgh2dkUw_07K0ak" title="6">
        <img alt="Sparkling Pool, Gated Community, Internet Access 6 thumbnail" onerror="this.onerror = null; this.src='/images/no_image.png'" src="https://images.craigslist.org/00R0R_4QRSgh2dkUw_07K0ak_50x50c.jpg"/>
       </a>
       <a class="thumb" data-imgid="j6CBLamaE5l_07K0ak" href="https://images.craigslist.org/00n0n_j6CBLamaE5l_07K0ak_600x450.jpg" id="7_thumb_j6CBLamaE5l_07K0ak" title="7">
        <img alt="Sparkling Pool, Gated Community, Internet Access 7 thumbnail" onerror="this.onerror = null; this.src='/images/no_image.png'" src="https://images.craigslist.org/00n0n_j6CBLamaE5l_07K0ak_50x50c.jpg"/>
       </a>
       <a class="thumb" data-imgid="4umFkMS0XC6_07K0ak" href="https://images.craigslist.org/00T0T_4umFkMS0XC6_07K0ak_600x450.jpg" id="8_thumb_4umFkMS0XC6_07K0ak" title="8">
        <img alt="Sparkling Pool, Gated Community, Internet Access 8 thumbnail" onerror="this.onerror = null; this.src='/images/no_image.png'" src="https://images.craigslist.org/00T0T_4umFkMS0XC6_07K0ak_50x50c.jpg"/>
       </a>
       <a class="thumb" data-imgid="5D9v6paEOYu_07K0ak" href="https://images.craigslist.org/00e0e_5D9v6paEOYu_07K0ak_600x450.jpg" id="9_thumb_5D9v6paEOYu_07K0ak" title="9">
        <img alt="Sparkling Pool, Gated Community, Internet Access 9 thumbnail" onerror="this.onerror = null; this.src='/images/no_image.png'" src="https://images.craigslist.org/00e0e_5D9v6paEOYu_07K0ak_50x50c.jpg"/>
       </a>
       <a class="thumb" data-imgid="eZnrnFO0xRd_07K0ak" href="https://images.craigslist.org/00202_eZnrnFO0xRd_07K0ak_600x450.jpg" id="10_thumb_eZnrnFO0xRd_07K0ak" title="10">

Most of the post is free-form text. So there's not going to be much value added by `BeautifulSoup`.

The exceptions are (i) parking, and (ii) the geographic coordinates.

<div class="alert alert-block alert-info">
    <strong>Exercise:</strong> Write a function that will return True if the apartment has no parking, and also returns the lat/lon of the apartment

*Hint*: First, create a `soup` object. Then, look and see what tag and class encloses this information. Then, you can experiment with `find` and `find_all` with this tag and class.

In [111]:
# your code here

parking = soup.find_all('div', class_='attrgroup')

In [112]:
print(parking)

[<div class="attrgroup">
<span class="attr important">
                1BR / 1Ba
            </span>
<span class="attr important">
                770ft<sup>2</sup>
</span>
<span class="attr important available-now">available now</span>
</div>, <div class="attrgroup">
<div class="attr rent_period">
<span class="labl">rent period:</span>
<span class="valu"> <a href="https://losangeles.craigslist.org/search/apa?rent_period=3">monthly</a>
</span>
</div>
</div>, <div class="attrgroup">
<div class="attr pets_cat">
<span class="valu"> <a href="https://losangeles.craigslist.org/search/apa?pets_cat=1">cats are OK - purrr</a>
</span>
</div>
<div class="attr">
<span class="valu"> <a href="https://losangeles.craigslist.org/search/apa?housing_type=1">apartment</a>
</span>
</div>
<div class="attr pets_dog">
<span class="valu"> <a href="https://losangeles.craigslist.org/search/apa?pets_dog=1">dogs are OK - wooof</a>
</span>
</div>
<div class="attr">
<span class="valu"> <a href="https://losangeles.craigslist.org/search/apa?laundry=3">laundry on site</a>
</span>
</div>
<div class="attr">
<span class="valu"> <a href="https://losangeles.craigslist.org/search/apa?parking=1">carport</a>
</span>
</div>
<div class="attr airconditioning">
<span class="valu"> <a href="https://losangeles.craigslist.org/search/apa?airconditioning=1">air conditioning</a>
</span>
</div>
</div>]

Now you've written this code, a next step would be to package it in a function that you can apply to all the URLs in your dataframe of posts (like the one we created in the video lecture).

## Large language models [Optional]

Large language models (LLMs) such as ChatGPT can also be accessed via an API.

The APIs are changing very rapidly, as are the pricing structures. For now, some LLMs are offered for free, for limited use. One such model with a free tier is Gemini, by Google.

If you'd like to experiment with Gemini, you need to [get an API key here](https://aistudio.google.com/u/1/apikey). No credit card is necessary, but your UCLA Google account won't work - you need a personal Google account.

[The documentation and some examples are here](https://github.com/googleapis/python-genai).

The other challenge with Gemini is that its Python library has several incompatibilities, including with some of the ones we use elsewhere in the course. So you will need to create a new environment in Anaconda, using the same setup process (importing an environment) as you did at the [start of the course](https://urbandatascience.its.ucla.edu/getting-started/).

Specifically:
- In Anaconda, go to the Environments tab
- Click on Import
- Choose `google-genai-env.yml` under Local Drive, and call the environment `genai`
- Manually add the `google-genai` package (choose "Not Installed", type `google-genai` into the search bar, select the checkbox, and then click Apply at the bottom of the screen)
- Anaconda will take some time, before you can click Apply again to install
- Close this notebook and open it again after you switch to your new `genai` environment

All set up? Let's look at a simple example---passing a query to the chat interface.

In [ ]:
from google import genai  # if this doesn't load, you probably have the wrong environment
gemini_api_key = 'XXXX' #'XXXXX' # fill in your key here

c = genai.Client(api_key=gemini_api_key)
chat = c.chats.create(model='gemini-2.0-flash-001')
response = chat.send_message('What do urban planners need to learn about gen AI?')
print(response.text)

How might this be used in web scraping? 

Well, perhaps you can ask it to parse the text.

<div class="alert alert-block alert-info">
    <strong>Exercise:</strong> Pass the text of the craiglist post to Gemini, and ask it to return the number of parking spaces (if any). Add the result to your dataframe. NOTE: This exercise is optional (you might not want to create a Google account to get an API key).

In [ ]:
# your code here

We won't do it here, but [you can also experiment with the MetaAI API](https://github.com/Strvm/meta-ai-api). The advantage: it doesn't need an API key, but the capabilities are a bit more limited. You can also find the Meta installed in the `genai` environment.

<div class="alert alert-block alert-info">
<h3>What you should have learned</h3>
<ul>
  <li>Gain confidence in experimenting with code - exploring different objects, writing functions, and so on</li>
  <li>Learn how to extract information from a scraped webpage - how to do the detective work.</li>
  <li>Gain confidence in debugging errors.</li>
  <li>Learn how to integrate Large Language Models into Python</li>
</ul>
</div>